---
language: python
sudo: required
services:
  - mysql
  - mongodb
  - postgresql
before_install:
  - wget https://repo.percona.com/apt/percona-release_latest.$(lsb_release -sc)_all.deb
  - sudo dpkg -i percona-release_latest.$(lsb_release -sc)_all.deb
  - sudo apt-get update
  - sudo apt-get install percona-xtrabackup-80
install:
  - pip install mysqlclient
  - python setup.py install
  - pip install pylint
script:
  - sudo ./scripts/travis_ci.sh
jobs:
  include:
    - stage: Test
      dist: focal
      name: "Python 3.8"
      python:
        - "3.8"
      before_script:
        - sleep 15
        - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
        - sudo apt-get install mongo-tools
    - stage: Test
      dist: focal
      name: "Python 3.7"
      python:
        - "3.7"
      before_script:
        - sleep 15
        - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
        - sudo apt-get install mongo-tools
    - stage: Test
      dist: focal
      name: "Python 3.6"
      python:
        - "3.6"
      before_script:
        - sleep 15
        - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
        - sudo apt-get install mongo-tools
    - stage: Docker
      name: "centos7_mariadb_10.5"
      services:
        - docker
      script: skip
      script: sudo ./scripts/travis_run_docker.sh centos7_mariadb_10.5
    - stage: Docker
      name: "centos7_mariadb_10.4"
      services:
        - docker
      script: skip
      script: sudo ./scripts/travis_run_docker.sh centos7_mariadb_10.4
    - stage: Docker
      name: "centos7_mariadb_10.3"
      services:
        - docker
      script: skip
      script: sudo ./scripts/travis_run_docker.sh centos7_mariadb_10.3
    - stage: Docker
      name: "centos7_mariadb_10"
      services:
        - docker
      script: skip
      script: sudo ./scripts/travis_run_docker.sh centos7_mariadb_10
    - stage: Docker
      name: "centos7_mariadb_5.5"
      services:
        - docker
      script: skip
      script: sudo ./scripts/travis_run_docker.sh centos7_mariadb_5.5
    - stage: Docker
      name: "centos7_mysql_5.6"
      services:
        - docker
      script: skip
      script: sudo ./scripts/travis_run_docker.sh centos7_mysql_5.6
    - stage: Docker
      name: "centos7_mysql_5.7"
      services:
        - docker
      script: skip
      script: sudo ./scripts/travis_run_docker.sh centos7_mysql_5.7
    - stage: Docker
      name: "centos7_mysql_8"
      services:
        - docker
      script: skip
      script: sudo ./scripts/travis_run_docker.sh centos7_mysql_8
    - stage: Docker
      name: "centos7_pgsql_9.2"
      services:
        - docker
      script: skip
      script: sudo ./scripts/travis_run_docker.sh centos7_pgsql_9.2
    - stage: Docker
      name: "centos7_pgsql_11"
      services:
        - docker
      script: skip
      script: sudo ./scripts/travis_run_docker.sh centos7_pgsql_11
